const sources={
 libro:{label:"Libro",data:["Autor o autores","Año","Título del libro","Editorial","DOI, si existe"],template:"Apellido, N. (Año). Título del libro. Editorial. DOI",example:"García, L. (2024). Tecnología y aprendizaje. Editorial Aula.",citation:"(García, 2024)",note:"El título del libro se escribe en cursivas. No se incluye la ciudad de la editorial."},
 articulo:{label:"Artículo académico",data:["Autor o autores","Año","Título del artículo","Nombre de la revista, volumen y número","Páginas","DOI o URL"],template:"Apellido, N. (Año). Título del artículo. Nombre de la Revista, volumen(número), páginas. https://doi.org/…",example:"López, M., & Ruiz, P. (2023). Pensamiento computacional en bachillerato. Revista de Educación Digital, 8(2), 25–40. https://doi.org/10.xxxx/xxxxx",citation:"(López & Ruiz, 2023)",note:"El nombre de la revista y el volumen van en cursivas; el número va entre paréntesis y no lleva cursivas."},
 web:{label:"Página web",data:["Autor personal o institución","Fecha disponible","Título de la página","Nombre del sitio, si difiere del autor","URL"],template:"Autor. (Año, día de mes). Título de la página. Nombre del sitio. URL",example:"Universidad Ejemplo. (2024, 15 de marzo). Ciudadanía digital para estudiantes. https://www.ejemplo.edu/ciudadania-digital",citation:"(Universidad Ejemplo, 2024)",note:"Si autor y nombre del sitio son iguales, no repitas el nombre del sitio. No agregues fecha de recuperación salvo que el contenido cambie con el tiempo."},
 noticia:{label:"Noticia digital",data:["Autor","Fecha completa","Título de la noticia","Nombre del periódico","URL"],template:"Apellido, N. (Año, día de mes). Título de la noticia. Nombre del Periódico. URL",example:"Pérez, A. (2024, 10 de abril). Estudiantes crean soluciones con robótica. Noticias Educativas. https://www.ejemplo.com/robotica",citation:"(Pérez, 2024)",note:"El nombre del periódico se escribe en cursivas."},
 pdf:{label:"Documento o PDF institucional",data:["Institución o autor","Año","Título del documento","Editorial o institución, si corresponde","URL"],template:"Institución. (Año). Título del documento. URL",example:"Secretaría de Educación Pública. (2024). Marco curricular común de la educación media superior. https://www.ejemplo.gob.mx/documento.pdf",citation:"(Secretaría de Educación Pública, 2024)",note:"PDF describe un formato de archivo, no un tipo de fuente. Identifica primero si el documento es un informe, libro, artículo u otro material."},
 youtube:{label:"Video de YouTube",data:["Autor o nombre del canal","Fecha completa","Título del video","Descripción [Video]","Plataforma","URL"],template:"Autor o canal. (Año, día de mes). Título del video [Video]. YouTube. URL",example:"Profe Charly. (2024, 20 de agosto). Introducción a los datos [Video]. YouTube. https://youtu.be/ejemplo",citation:"(Profe Charly, 2024)",note:"Usa el nombre del canal como autor tal como aparece en YouTube."},
 imagen:{label:"Imagen o fotografía en línea",data:["Autor","Fecha","Título o descripción","Tipo de obra entre corchetes","Sitio o colección","URL"],template:"Autor. (Año). Título de la imagen [Fotografía]. Sitio. URL",example:"Ramírez, C. (2023). Robot educativo en el aula [Fotografía]. Archivo STEAM. https://www.ejemplo.org/robot",citation:"(Ramírez, 2023)",note:"La forma exacta depende de dónde se obtuvo la imagen. No cites Google Imágenes: cita la página original que aloja la obra."},
 profesor:{label:"Material del profesor",data:["Autor","Fecha","Título","Descripción del formato","Institución o plataforma, según disponibilidad"],template:"Apellido, N. (Año). Título del material [Diapositivas de clase]. Institución.",example:"Arellano Ponce, J. C. (2026). Organización y depuración de datos [Diapositivas de clase]. Preparatoria Amozoc, BUAP.",citation:"(Arellano Ponce, 2026)",note:"Si el material no puede ser recuperado por el lector, algunas actividades pueden tratarlo como comunicación personal. Sigue la indicación del profesor."},
 ia:{label:"Inteligencia artificial generativa",data:["Autor de la herramienta","Fecha o versión","Nombre del modelo o herramienta","Descripción [Modelo de lenguaje grande]","URL"],template:"Organización. (Año). Nombre de la herramienta (versión) [Modelo de lenguaje grande]. URL",example:"OpenAI. (2026). ChatGPT [Modelo de lenguaje grande]. https://chatgpt.com/",citation:"(OpenAI, 2026)",note:"Describe también en el texto cómo utilizaste la herramienta y conserva los resultados cuando tu actividad lo requiera. Verifica la versión y las reglas indicadas por tu profesor."}
};
const select=document.querySelector('#source-type');
function showSource(){const s=sources[select.value];document.querySelector('#source-label').textContent=s.label;document.querySelector('#needed-data').innerHTML=s.data.map(x=>`<li>${x}</li>`).join('');document.querySelector('#source-template').textContent=s.template;document.querySelector('#source-example').textContent=s.example;document.querySelector('#source-citation').textContent=s.citation;document.querySelector('#source-note').textContent=s.note}select.addEventListener('change',showSource);showSource();
document.querySelectorAll('.tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.querySelector(`#${button.dataset.tab}`).classList.add('active')}));
const questions=[
 {q:"Sofía incluyó un libro en sus referencias, pero nunca usó información de él en su texto. ¿Qué debe hacer?",o:["Dejarlo para demostrar que investigó","Citarlo donde utilizó su información o retirarlo","Cambiarlo por un enlace","Moverlo a la portada"],a:1,f:"Las referencias deben corresponder a fuentes realmente utilizadas y citadas."},
 {q:"Reescribiste con tus propias palabras una idea de García. ¿Necesitas citarla?",o:["Sí, porque la idea proviene de otra fuente","No, porque ya no usaste las mismas palabras","Solo si ocupa más de 40 palabras","Solo si es un libro"],a:0,f:"La paráfrasis cambia la redacción, no la autoría de la idea."},
 {q:"¿Cuál es una cita parentética correcta para una obra de García publicada en 2024?",o:["García, L. Tecnología y aprendizaje","(García, 2024)","www.garcia.com","Referencias: García"],a:1,f:"La cita parentética básica incluye apellido y año entre paréntesis."},
 {q:"Una cita textual tiene 25 palabras. ¿Cómo debe presentarse?",o:["En bloque y sin comillas","Con comillas e indicando un localizador","Sin cita si aparece la referencia","Solo con el enlace"],a:1,f:"Las citas textuales de menos de 40 palabras se integran entre comillas y llevan autor, año y localizador."},
 {q:"¿Qué elemento NO debe inventarse cuando falta en una fuente?",o:["El autor o la fecha","La sangría francesa","El orden alfabético","El título Referencias"],a:0,f:"APA contempla información faltante. Nunca inventes datos bibliográficos."}
];let qi=0,score=0,answered=false;const qText=document.querySelector('#quiz-question'),qOptions=document.querySelector('#quiz-options'),feedback=document.querySelector('#quiz-feedback'),next=document.querySelector('#quiz-next');
function renderQuiz(){answered=false;const q=questions[qi];document.querySelector('#quiz-number').textContent=`Pregunta ${qi+1} de ${questions.length}`;document.querySelector('#quiz-score').textContent=`Aciertos: ${score}`;qText.textContent=q.q;feedback.textContent='';feedback.className='quiz-feedback';next.hidden=true;qOptions.innerHTML='';q.o.forEach((opt,i)=>{const b=document.createElement('button');b.className='quiz-option';b.textContent=opt;b.addEventListener('click',()=>answer(i,b));qOptions.appendChild(b)})}
function answer(i,b){if(answered)return;answered=true;const q=questions[qi];qOptions.querySelectorAll('button').forEach((x,n)=>{x.disabled=true;if(n===q.a)x.classList.add('correct')});if(i===q.a){score++;feedback.textContent=`¡Correcto! ${q.f}`;feedback.classList.add('good')}else{b.classList.add('wrong');feedback.textContent=`Revisa: ${q.f}`;feedback.classList.add('bad')}document.querySelector('#quiz-score').textContent=`Aciertos: ${score}`;next.textContent=qi===questions.length-1?'Ver resultado':'Siguiente pregunta →';next.hidden=false}
next.addEventListener('click',()=>{
  if(qi<questions.length-1){qi++;renderQuiz();return}
  qText.textContent=`Resultado: ${score} de ${questions.length}`;
  qOptions.innerHTML='';
  feedback.textContent=score===questions.length?'¡Excelente! Ya dominas las ideas esenciales.':'Puedes volver a intentarlo y consultar los apartados anteriores.';
  feedback.className='quiz-feedback good';
  next.textContent='Intentar nuevamente';
  next.onclick=()=>{qi=0;score=0;next.onclick=null;renderQuiz()};
});
renderQuiz();
document.querySelector('#copy-prompt').addEventListener('click',async e=>{const t=document.querySelector('#socratic-prompt');try{await navigator.clipboard.writeText(t.value);e.currentTarget.textContent='¡Prompt copiado!'}catch{t.select();document.execCommand('copy');e.currentTarget.textContent='¡Prompt copiado!'}setTimeout(()=>e.currentTarget.textContent='Copiar prompt',1800)});
